services:

  api:
    build:
      context: .
      dockerfile: Firmeza.Api/Dockerfile
    container_name: firmeza_api
    restart: on-failure
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  admin:
    build:
      context: .
      dockerfile: Firmeza.web/Dockerfile
    container_name: firmeza_admin
    restart: on-failure
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  client:
    build:
      context: ./Firmeza.Client
      dockerfile: Dockerfile
    container_name: firmeza_client
    restart: on-failure
    ports:
      - "4200:80"
    depends_on:
      api:
        condition: service_started
