services:
  db:
    image: postgres:16
    container_name: firmeza-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: firmeza
    ports:
      - "5434:5432"
    volumes:
      - firmeza_pg_data:/var/lib/postgresql/data

volumes:
  firmeza_pg_data:
